In [1]:
import pandas as pd
import numpy as np
from selenium import webdriver
import time
from selenium.common.exceptions import NoSuchElementException
from selenium.common.exceptions import StaleElementReferenceException 
from selenium.common.exceptions import ElementNotVisibleException
from selenium.common.exceptions import ElementNotInteractableException
from selenium.common.exceptions import SessionNotCreatedException
from selenium.common.exceptions import TimeoutException
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as ec
from selenium.webdriver.common.by import By
import time
import warnings
warnings.filterwarnings('ignore')

# Q1. Scrape the details of most viewed videos on YouTube from Wikipedia.Url = https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos . You need to find following details:
A) Rank
B) Name
C) Artist
D) Upload date
E) Views

In [63]:
driver=webdriver.Chrome(r'C:\Users\shaik\Downloads\chromedriver_win32\chromedriver.exe')
driver.get('https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos')
time.sleep(3)

In [65]:
count=0
view=[]
date=[]
#pd.DataFrame(data=driver.find_element_by_xpath('//table[@class="wikitable sortable jquery-tablesorter"]'))
data=driver.find_element_by_xpath('//table[@class="wikitable sortable jquery-tablesorter"]').text.split('\n')
temp
for i in driver.find_elements_by_xpath('//td'):
    temp.append(i.text)
del data[0:2]
del data[-1]

pd.DataFrame(temp)
pd.DataFrame(data)

                                                    0
0   1. "Baby Shark Dance"[3] Pinkfong Baby Shark -...
1   2. "Despacito"[6] Luis Fonsi 7.82 January 12, ...
2   3. "Johny Johny Yes Papa"[12] LooLoo Kids 6.31...
3   4. "Shape of You"[13] Ed Sheeran 5.69 January ...
4   5. "See You Again"[15] Wiz Khalifa 5.48 April ...
5   6. "Bath Song"[20] Cocomelon – Nursery Rhymes ...
6   7. "Phonics Song with Two Words"[21] ChuChu TV...
7   8. "Learning Colors – Colorful Eggs on a Farm"...
8   9. "Uptown Funk"[23] Mark Ronson 4.54 November...
9   10. "Masha and the Bear – Recipe for Disaster"...
10  11. "Gangnam Style"[25] Psy 4.40 July 15, 2012...
11  12. "Wheels on the Bus"[30] Cocomelon – Nurser...
12  13. "Dame Tu Cosita"[31] El Chombo 3.92 April ...
13     14. "Sugar"[32] Maroon 5 3.68 January 14, 2015
14   15. "Roar"[33] Katy Perry 3.56 September 5, 2013
15  16. "Counting Stars"[34] OneRepublic 3.56 May ...
16  17. "Sorry"[35] Justin Bieber 3.54 October 22,...
17  18. "Thinking Out Loud"[36] Ed Sheeran 3.44 Oc...
18     19. "Axel F"[37] Crazy Frog 3.32 June 16, 2009
19  20. "Girls Like You"[38] Maroon 5 3.28 May 31,...
20  21. "Faded"[39] Alan Walker 3.27 December 3, 2015
21  22. "Dark Horse"[40] Katy Perry 3.26 February ...
22  23. "Let Her Go"[41] Passenger 3.21 July 25, 2012
23  24. "Baa Baa Black Sheep"[42] Cocomelon – Nurs...
24  25. "Bailando"[43] Enrique Iglesias 3.19 April...
25  26. "Lean On"[44] Major Lazer 3.19 March 22, 2015
26  27. "Shake It Off"[45] Taylor Swift 3.16 Augus...
27  28. "Perfect"[46] Ed Sheeran 3.14 November 9, ...
28  29. "Waka Waka (This Time for Africa)"[47] Sha...
29     30. "Mi Gente"[48] J Balvin 3.07 June 29, 2017

# Q2. Scrape the details team India’s international fixtures from bcci.tv. Url = https://www.bcci.tv/. You need to find following details:
A) Match title (I.e. 1st ODI)
B) Series
C) Place
D) Date
E) Time

In [67]:
driver=webdriver.Chrome(r'C:\Users\shaik\Downloads\chromedriver_win32\chromedriver.exe')
driver.get('https://www.bcci.tv/')
time.sleep(3)
driver.find_element_by_xpath('/html/body/nav/div/div[2]/ul[1]/li[2]/a').click()

In [76]:
title=[]
stadium=[]
place=[]
series=[]
date=[]
time=[]
for i in driver.find_elements_by_xpath('//h5[@class="ng-binding"]'):
    date.append(i.text)
for i in driver.find_elements_by_xpath('//h5[@class="text-right ng-binding"]'):
    time.append(i.text)
for i in driver.find_elements_by_xpath('//span[@class="ng-binding ng-scope"]'):
    stadium.append(i.text)
for i in driver.find_elements_by_xpath('//span[@class="ng-binding"]'):
    series.append(i.text)
for i in driver.find_elements_by_xpath('//div[@class="fix-place ng-binding ng-scope"]'):
    temp=i.text.split('-')
    title.append(temp[0])
    place.append(temp[1])
    
pd.DataFrame({'Title':title,'Series':series,'Place':place,'Date':date,'Time':time})

,Title,Series,Place,Date,Time
0,1st T20I,SOUTH AFRICA TOUR OF INDIA T20 SERIES 2022,"Arun Jaitley Stadium, Delhi",9 JUN 2022,7:30 PM IST
1,2nd T20I,SOUTH AFRICA TOUR OF INDIA T20 SERIES 2022,"Barabati Stadium, Cuttack",12 JUN 2022,7:30 PM IST
2,3rd T20I,SOUTH AFRICA TOUR OF INDIA T20 SERIES 2022,Dr YS Rajasekhara Reddy ACA,14 JUN 2022,7:30 PM IST
3,4th T20I,SOUTH AFRICA TOUR OF INDIA T20 SERIES 2022,"Saurashtra Cricket Association Stadium, Rajkot",17 JUN 2022,7:30 PM IST
4,5th T20I,SOUTH AFRICA TOUR OF INDIA T20 SERIES 2022,"M Chinnaswamy Stadium, Bengaluru",19 JUN 2022,7:30 PM IST

In [77]:
driver.close()

# Q3. Scrape the details of selenium exception from guru99.com. Url = https://www.guru99.com/ . You need to find following details:
A) Name
B) Description

In [3]:
driver=webdriver.Chrome(r'C:\Users\shaik\Downloads\chromedriver_win32\chromedriver.exe')
driver.get('https://www.guru99.com/exception-handling-selenium.html')
time.sleep(3)
#driver.find_element_by_xpath('//*[@id="gsc-i-id1"]').send_keys('selenium exception handling')
#driver.find_element_by_xpath('/html/body/div[1]/div/div/div/main/div/article/div/div[1]/div[1]/div[2]/div/div[1]/div/div/div/form/table/tbody/tr/td[2]/button').click()
#driver.find_element_by_xpath('/html/body/div[1]/div/div/div/main/div/article/div/div[1]/div[1]/div[2]/div/div[1]/div/div/div/div[1]/div[6]/div[2]/div/div/div[1]/div[1]/div[1]/div[1]/div/a').click()

In [6]:
name=[]
des=[]
count=0
for i in driver.find_elements_by_xpath('//td'):
    count+=1
    if count%2==1:
        name.append(i.text)
    elif count%2==0:
        des.append(i.text)
pd.DataFrame({'Exception Name':name,'Description':des})

,Exception Name,Description
0,ElementNotVisibleException,This type of Selenium exception occurs when an...
1,ElementNotSelectableException,This Selenium exception occurs when an element...
2,NoSuchElementException,This Exception occurs if an element could not ...
3,NoSuchFrameException,This Exception occurs if the frame target to b...
4,NoAlertPresentException,This Exception occurs when you switch to no pr...
5,NoSuchWindowException,This Exception occurs if the window target to ...
6,StaleElementReferenceException,This Selenium exception occurs happens when th...
7,SessionNotFoundException,The WebDriver is acting after you quit the bro...
8,TimeoutException,Thrown when there is not enough time for a com...
9,WebDriverException,This Exception takes place when the WebDriver ...
10,ConnectionClosedException,This type of Exception takes place when there ...
11,ElementClickInterceptedException,The command may not be completed as the elemen...
12,ElementNotInteractableException,This Selenium exception is thrown when any ele...
13,ErrorInResponseException,This happens while interacting with the Firefo...
14,ErrorHandler.UnknownServerException,Exception is used as a placeholder in case if ...
15,ImeActivationFailedException,This expectation will occur when IME engine ac...
16,ImeNotAvailableException,It takes place when IME support is unavailable.
17,InsecureCertificateException,Navigation made the user agent to hit a certif...
18,InvalidArgumentException,It occurs when an argument does not belong to ...
19,InvalidCookieDomainException,This happens when you try to add a cookie unde...
20,InvalidCoordinatesException,This type of Exception matches an interacting ...
21,InvalidElementStateExceptio,It occurs when command can’t be finished when ...
22,InvalidSessionIdException,This Exception took place when the given sessi...
23,InvalidSwitchToTargetException,This occurs when the frame or window target to...
24,JavascriptException,This issue occurs while executing JavaScript g...
25,JsonException,It occurs when you afford to get the session w...
26,NoSuchAttributeException,This kind of Exception occurs when the attribu...
27,MoveTargetOutOfBoundsException,It takes place if the target provided to the A...
28,NoSuchContextException,ContextAware does mobile device testing.
29,NoSuchCookieException,This Exception occurs when no cookie matching ...
30,NotFoundException,This Exception is a subclass of WebDriverExcep...
31,RemoteDriverServerException,This Selenium exception is thrown when the ser...
32,ScreenshotException,It is not possible to capture a screen.
33,SessionNotCreatedException,It happens when a new session could not be suc...
34,UnableToSetCookieException,This occurs if a driver is unable to set a coo...
35,UnexpectedTagNameException,Happens if a support class did not get a web e...
36,UnhandledAlertException,This expectation occurs when there is an alert...
37,UnexpectedAlertPresentException,It occurs when there is the appearance of an u...
38,UnknownMethodException,This Exception happens when the requested comm...
39,UnreachableBrowserException,This Exception occurs only when the browser is...
40,UnsupportedCommandException,This occurs when remote WebDriver does n’t sen...

In [ ]:
driver.close()

# Q4.Scrape the details of State-wise GDP of India from statisticstime.com. Url = http://statisticstimes.com/ You have to find following details:
A) Rank
B) State
C) GSDP(18-19)
D) GSDP(17-18)
E) Share(2017)
F) GDP($ billion)

In [4]:
driver=webdriver.Chrome(r'C:\Users\shaik\Downloads\chromedriver_win32\chromedriver.exe')
driver.get('https://www.statisticstimes.com/economy/india/indian-states-gdp.php')
time.sleep(3)

SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 99
Current browser version is 101.0.4951.54 with binary path C:\Program Files\Google\Chrome\Application\chrome.exe
Stacktrace:
Backtrace:
	Ordinal0 [0x00C09943+2595139]
	Ordinal0 [0x00B9C9F1+2148849]
	Ordinal0 [0x00A94528+1066280]
	Ordinal0 [0x00AB42C3+1196739]
	Ordinal0 [0x00AAFE37+1179191]
	Ordinal0 [0x00AAD6F1+1169137]
	Ordinal0 [0x00AE0530+1377584]
	Ordinal0 [0x00AE018A+1376650]
	Ordinal0 [0x00ADB806+1357830]
	Ordinal0 [0x00AB6086+1204358]
	Ordinal0 [0x00AB6F96+1208214]
	GetHandleVerifier [0x00DAB232+1658114]
	GetHandleVerifier [0x00E6312C+2411516]
	GetHandleVerifier [0x00C9F261+560433]
	GetHandleVerifier [0x00C9E366+556598]
	Ordinal0 [0x00BA286B+2173035]
	Ordinal0 [0x00BA75F8+2192888]
	Ordinal0 [0x00BA76E5+2193125]
	Ordinal0 [0x00BB11FC+2232828]
	BaseThreadInitThunk [0x76E86739+25]
	RtlGetFullPathName_UEx [0x77778E7F+1215]
	RtlGetFullPathName_UEx [0x77778E4D+1165]

In [45]:
count=0
rank=[]
c=0
state=[]
gsdp1=[]
gsdp2=[]
share=[]
gdp=[]
for i in driver.find_elements_by_xpath('//td'):
    count+=1
    if count>=4:
        if (count-4)%8==2:
            state.append(i.text)
            c+=1
            rank.append(c)
        if (count-4)%8==3:
            gsdp2.append(i.text)
        if (count-4)%8==4:
            gsdp1.append(i.text)
        if (count-4)%8==5:
            share.append(i.text)
        if (count-4)%8==6:
            gdp.append(i.text)
    if count==8*33+4:
        break
pd.DataFrame({'Rank':rank,'State Name':state,'GSDP(19-20)':gsdp2,'GSDP(18-19)':gsdp1,'Share':share,'GDP':gdp}).set_index('Rank')

                     State Name GSDP(19-20) GSDP(18-19)   Share      GDP
Rank
1                   Maharashtra           -   2,632,792  13.94%  399.921
2                    Tamil Nadu   1,845,853   1,630,208   8.63%  247.629
3                 Uttar Pradesh   1,687,818   1,584,764   8.39%  240.726
4                       Gujarat           -   1,502,899   7.96%  228.290
5                     Karnataka   1,631,977   1,493,127   7.91%  226.806
6                   West Bengal   1,253,832   1,089,898   5.77%  165.556
7                     Rajasthan   1,020,989     942,586   4.99%  143.179
8                Andhra Pradesh     972,782     862,957   4.57%  131.083
9                     Telangana     969,604     861,031   4.56%  130.791
10               Madhya Pradesh     906,672     809,592   4.29%  122.977
11                       Kerala           -     781,653   4.14%  118.733
12                        Delhi     856,112     774,870   4.10%  117.703
13                      Haryana     831,610     734,163   3.89%  111.519
14                        Bihar     611,804     530,363   2.81%   80.562
15                       Punjab     574,760     526,376   2.79%   79.957
16                       Odisha     521,275     487,805   2.58%   74.098
17                        Assam           -     315,881   1.67%   47.982
18                 Chhattisgarh     329,180     304,063   1.61%   46.187
19                    Jharkhand     328,598     297,204   1.57%   45.145
20                  Uttarakhand           -     245,895   1.30%   37.351
21              Jammu & Kashmir           -     155,956   0.83%   23.690
22             Himachal Pradesh     165,472     153,845   0.81%   23.369
23                          Goa      80,449      73,170   0.39%   11.115
24                      Tripura      55,984      49,845   0.26%    7.571
25                   Chandigarh           -      42,114   0.22%    6.397
26                   Puducherry      38,253      34,433   0.18%    5.230
27                    Meghalaya      36,572      33,481   0.18%    5.086
28                       Sikkim      32,496      28,723   0.15%    4.363
29                      Manipur      31,790      27,870   0.15%    4.233
30                     Nagaland           -      27,283   0.14%    4.144
31            Arunachal Pradesh           -      24,603   0.13%    3.737
32                      Mizoram      26,503      22,287   0.12%    3.385
33    Andaman & Nicobar Islands           -           -       -        -

In [46]:
driver.close()

# Q6. Scrape the details of top 100 songs on billiboard.com. Url = https:/www.billboard.com/ .You have to find the following details:
A) Song name
B) Artist name
C) Last week rank
D) Peak rank
E) Weeks on board

In [2]:
driver=webdriver.Chrome(r'C:\Users\shaik\Downloads\chromedriver_win32\chromedriver.exe')
driver.get('https://www.billboard.com/charts/hot-100/')

SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 99
Current browser version is 101.0.4951.54 with binary path C:\Program Files\Google\Chrome\Application\chrome.exe
Stacktrace:
Backtrace:
	Ordinal0 [0x00349943+2595139]
	Ordinal0 [0x002DC9F1+2148849]
	Ordinal0 [0x001D4528+1066280]
	Ordinal0 [0x001F42C3+1196739]
	Ordinal0 [0x001EFE37+1179191]
	Ordinal0 [0x001ED6F1+1169137]
	Ordinal0 [0x00220530+1377584]
	Ordinal0 [0x0022018A+1376650]
	Ordinal0 [0x0021B806+1357830]
	Ordinal0 [0x001F6086+1204358]
	Ordinal0 [0x001F6F96+1208214]
	GetHandleVerifier [0x004EB232+1658114]
	GetHandleVerifier [0x005A312C+2411516]
	GetHandleVerifier [0x003DF261+560433]
	GetHandleVerifier [0x003DE366+556598]
	Ordinal0 [0x002E286B+2173035]
	Ordinal0 [0x002E75F8+2192888]
	Ordinal0 [0x002E76E5+2193125]
	Ordinal0 [0x002F11FC+2232828]
	BaseThreadInitThunk [0x76356739+25]
	RtlGetFullPathName_UEx [0x77328E7F+1215]
	RtlGetFullPathName_UEx [0x77328E4D+1165]
	(No symbol) [0x00000000]

In [70]:
name=[]
song=[]
lweek=[]
peak=[]
wob=[]
data=[]
name.append(driver.find_element_by_xpath('//span[@class="c-label  a-no-trucate a-font-primary-s lrv-u-font-size-14@mobile-max u-line-height-normal@mobile-max u-letter-spacing-0021 lrv-u-display-block a-truncate-ellipsis-2line u-max-width-330 u-max-width-230@tablet-only u-font-size-20@tablet"]').text)
song.append(driver.find_element_by_xpath('//h3[@class="c-title  a-no-trucate a-font-primary-bold-s u-letter-spacing-0021 u-font-size-23@tablet lrv-u-font-size-16 u-line-height-125 u-line-height-normal@mobile-max a-truncate-ellipsis u-max-width-245 u-max-width-230@tablet-only u-letter-spacing-0028@tablet"]').text)
lweek.append(driver.find_element_by_xpath('//li[@class="o-chart-results-list__item // a-chart-color u-width-72 u-width-55@mobile-max u-width-55@tablet-only lrv-u-flex lrv-u-flex-shrink-0 lrv-u-align-items-center lrv-u-justify-content-center lrv-u-border-b-1 u-border-b-0@mobile-max lrv-u-border-color-grey-light u-background-color-white-064@mobile-max u-hidden@mobile-max"]').text)
peak.append(driver.find_element_by_xpath('//span[@class="c-label  a-font-primary-bold-l a-font-primary-m@mobile-max u-font-weight-normal@mobile-max lrv-u-padding-tb-050@mobile-max u-font-size-32@tablet"]').text)
wob.append(driver.find_element_by_xpath('//span[@class="c-label  a-font-primary-bold-l a-font-primary-m@mobile-max u-font-weight-normal@mobile-max lrv-u-padding-tb-050@mobile-max u-font-size-32@tablet"]').text)

for i in driver.find_elements_by_xpath('//span[@class="c-label  a-no-trucate a-font-primary-s lrv-u-font-size-14@mobile-max u-line-height-normal@mobile-max u-letter-spacing-0021 lrv-u-display-block a-truncate-ellipsis-2line u-max-width-330 u-max-width-230@tablet-only"]'):
    name.append(i.text)
for i in driver.find_elements_by_xpath('//h3[@class="c-title  a-no-trucate a-font-primary-bold-s u-letter-spacing-0021 lrv-u-font-size-18@tablet lrv-u-font-size-16 u-line-height-125 u-line-height-normal@mobile-max a-truncate-ellipsis u-max-width-330 u-max-width-230@tablet-only"]'):
    song.append(i.text)
for i in driver.find_elements_by_xpath('//span[@class="c-label  a-font-primary-m lrv-u-padding-tb-050@mobile-max"]'):
    data.append(i.text)
data = list(filter(None, data))
for i in range(0,len(data),1):
    if (i+1)%3==1:
        lweek.append(data[i])
    elif(i+1)%3==2:
        peak.append(data[i])
    elif(i+1)%3==0:
        wob.append(data[i])
rank=[]
for i in range(1,101):
    rank.append(i)
pd.DataFrame({'Rank':rank,'Artist':name,'Song':song,'Last Week Rank':lweek,'Peak Rank':peak,'Weeks On Board':wob}).set_index('Rank')

,Artist,Song,Last Week Rank,Peak Rank,Weeks On Board
Rank,,,,,
1,Harry Styles,As It Was,2,2,2
2,Jack Harlow,First Class,1,1,2
3,Glass Animals,Heat Waves,3,1,66
4,Latto,Big Energy,4,3,26
5,Imagine Dragons X JID,Enemy,5,5,22
...,...,...,...,...,...
96,Gunna Featuring Drake,P Power,91,24,14
97,Yeat,Money So Big,-,95,4
98,Coi Leray & Nicki Minaj,Blick Blick!,95,37,4
99,Bailey Zimmerman,Fall In Love,-,99,1
100,Daddy Yankee & Bad Bunny,X Ultima Vez,99,73,3

In [71]:
driver.close()

# Q7. Scrape the details of Data science recruiters from naukri.com. Url = https://www.naukri.com/ .You have to find the following details:
A) Name
B) Designation
C) Company
D) Skills they hire for
E) Location

In [46]:
driver=webdriver.Chrome(r'C:\Users\shaik\Downloads\chromedriver_win32\chromedriver.exe')
driver.get('https://www.naukri.com/')
time.sleep(3)
driver.find_element_by_class_name('suggestor-input').send_keys('Data Scientist')
driver.find_element_by_xpath('/html/body/div/div[2]/div[3]/div/div/div[6]').click()

In [53]:
title=[]
loc=[]
company=[]
decr=[]
skill=[]
for i in driver.find_elements_by_xpath('//a[@class="title fw500 ellipsis"]'):
    title.append(i.text)
    
for i in driver.find_elements_by_xpath('//a[@class="subTitle ellipsis fleft"]'):
    company.append(i.text)
    
for i in driver.find_elements_by_xpath('//li[@class="fleft grey-text br2 placeHolderLi location"]'):
    loc.append(i.text)
    
for i in driver.find_elements_by_xpath('//div[@class="job-description fs12 grey-text"]'):
    decr.append(i.text)
    
for i in driver.find_elements_by_xpath('//ul[@class="tags has-description"]'):
    skill.append(i.text)
    
pd.DataFrame({'Job Title':title,'Company Name':company,'Job Description':decr,'Skills Needed':skill,'Location':loc})

,Job Title,Company Name,Job Description,Skills Needed,Location
0,Senior Data Scientist,Walmart,BE/ BTech/ MTech / MS/PhD from a reputed insti...,IT Skills\nTesting\nData Science\nMachine Lear...,Bangalore/Bengaluru
1,Data Scientist,Applied Materials,"Acquire, cleanse, organize and mine massive vo...",Unix\nsemiconductor\nJMP\nanalyzing data\nstat...,Bangalore/Bengaluru
2,Digital-Associate Process Manager - Data Scien...,eClerx,Shift TimingsThe candidate must possess in-dep...,Data Scientist\nIT Skills\nProject Management\...,Pune
3,Senior Data Scientist (IN4),Walmart,Master s/ PhD or any other graduation degree w...,IT Skills\nPython\nSoftware Development\nTesti...,Bangalore/Bengaluru
4,Senior Data Scientist,Walmart,Your Opportunity As a Senior Data Scientist fo...,IT Skills\nPython\nData Science\nMachine Learn...,Bangalore/Bengaluru
5,Senior Data Scientist,Ericsson Global Services,To be successful in the role you must have,Bidding\nGoogle Analytics\nData management\nSo...,Bangalore/Bengaluru
6,Data Analyst / Data Scientist,GSOURCE TECHNOLOGIES PRIVATE LIMITED,Roles and Responsibilities Work with operation...,excel\nData Analysis\nData Visualization\nTabl...,Pune(Kalyani Nagar)
7,Associate Data Scientist,IDFC FIRST Bank,Job Requirements - Experience Experience Minim...,Economics\nstats Graduate\nData scientist\nMac...,"Mumbai, Pune, Bangalore/Bengaluru, Mumbai"
8,Lead Data Scientist,Groww,Key Responsibilities: A Staff Data Scientist i...,data science\nMachine learning\nConsulting\nMa...,Bangalore/Bengaluru
9,Staff Engineer Data Scientist,Infineon Technologies Pvt Ltd,"Bachelors / Master Degree in Computer Science,...",Computer science\nText mining\nData analysis\n...,Bangalore/Bengaluru
10,Senior Data Scientist,Truecaller,As a Senior Data Scientist you will be respons...,GCP\nAnalytical\nMachine learning\nSMS\nAgile\...,Bangalore/Bengaluru
11,Senior Data Scientist,PayU,"Bachelors in mathematics, statistics or comput...",SAS\nSocial media\nAnalytical\nData collection...,Bangalore/Bengaluru
12,Senior Data Scientist,Gojek,PhD or Masters in a quantitative discipline At...,deep learning\nPrototype\ndata science\nAnalyt...,Bangalore/Bengaluru
13,ASSOCIATE DATA SCIENTIST,Hinduja Global,Qualification : M Sc in Statistics/Mathematics...,Text mining\nMS SQL\nStatistical analysis\nMyS...,Bangalore/Bengaluru
14,Analyst - Data Scientist,UPL,2 + years experience with popular database pro...,Python\nTensorflow\nData Science\nNLP\nHadoop\...,Mumbai
15,Senior Data Scientist,ICERTIS Solutions,Build predictive models that are accurate and ...,IT Skills\nPython\nData Science\nMachine Learn...,Pune
16,"Data Scientist (BFSI) - MySQL, MIS QC",Muthoot Microfin,The company is focused on providing micro-loan...,Predictive Modeling\nPower Bi\nBusiness Analyt...,"Kochi/Cochin, Ernakulam"
17,Data Scientist,Muthoot Microfin,The company is focused on providing micro-loan...,Predictive Modeling\nBusiness Intelligence\nPo...,"Kochi/Cochin, Ernakulam"
18,Urgent Opening For Data Scientist - Machine Le...,SPI technologies india private limited,Shift - Flexible shift timing( 9hrs of Working...,python\nnlp\nmachine learning\ndata engineerin...,Chennai
19,Rolls-Royce Data Labs : Data Scientist,Rolls Royce,More than 3 years experience in developing and...,Matplotlib\nAzure\nGIT\nLinux\nDocker\nPandas\...,Bangalore/Bengaluru

In [54]:
driver.close()

# Q8. Scrape the details of Highest selling novels. Url = https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-grey-compare/ .You have to find the following details:
A) Book name
B) Author name
C) Volumes sold
D) Publisher
E) Genre

In [74]:
driver=webdriver.Chrome(r'C:\Users\shaik\Downloads\chromedriver_win32\chromedriver.exe')
driver.get('https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-grey-compare')
time.sleep(3)

In [76]:
data=[]
genre=[]
rank=[]
book=[]
author=[]
sold=[]
pub=[]
count=0
for i in driver.find_elements_by_xpath('//td[@class="left"]'):
    count+=1
    if count%5==1:
        rank.append(i.text)
    elif count%5==2:
        book.append(i.text)
    elif count%5==3:
        author.append(i.text)
    elif count%5==4:
        sold.append(i.text)
    elif count%5==0:
        pub.append(i.text)

for i in driver.find_elements_by_xpath('//td[@class="last left"]'):
    genre.append(i.text)
pd.DataFrame({'Rank':rank,'Book Name':book,'Author Name':author,'Volumes Sold':sold,'Publisher':pub,'Genre':genre}).set_index('Rank')

,Book Name,Author Name,Volumes Sold,Publisher,Genre
Rank,,,,,
1,"Da Vinci Code,The","Brown, Dan","5,094,805",Transworld,"Crime, Thriller & Adventure"
2,Harry Potter and the Deathly Hallows,"Rowling, J.K.","4,475,152",Bloomsbury,Children's Fiction
3,Harry Potter and the Philosopher's Stone,"Rowling, J.K.","4,200,654",Bloomsbury,Children's Fiction
4,Harry Potter and the Order of the Phoenix,"Rowling, J.K.","4,179,479",Bloomsbury,Children's Fiction
5,Fifty Shades of Grey,"James, E. L.","3,758,936",Random House,Romance & Sagas
...,...,...,...,...,...
96,"Ghost,The","Harris, Robert","807,311",Random House,General & Literary Fiction
97,Happy Days with the Naked Chef,"Oliver, Jamie","794,201",Penguin,Food & Drink: General
98,"Hunger Games,The:Hunger Games Trilogy","Collins, Suzanne","792,187",Scholastic Ltd.,Young Adult Fiction
99,"Lost Boy,The:A Foster Child's Search for the L...","Pelzer, Dave","791,507",Orion,Biography: General
100,Jamie's Ministry of Food:Anyone Can Learn to C...,"Oliver, Jamie","791,095",Penguin,Food & Drink: General

In [77]:
driver.close()

# Q9. Scrape the details most watched tv series of all time from imdb.com. Url = https://www.imdb.com/list/ls095964455/ .You have to find the following details:
A) Name
B) Year span
C) Genre
D) Run time
E) Ratings
F) Votes

In [79]:
driver=webdriver.Chrome(r'C:\Users\shaik\Downloads\chromedriver_win32\chromedriver.exe')
driver.get('https://www.imdb.com/list/ls095964455/')

In [113]:
data=[]
year=[]
rt=[]
genre=[]
ratings=[]
votes=[]
for i in driver.find_elements_by_xpath('//h3[@class="lister-item-header"]'):
    temp=i.text
    data.append(temp.split('(')[0])
for i in driver.find_elements_by_xpath('//span[@class="lister-item-year text-muted unbold"]'):
    year.append(i.text)
for i in driver.find_elements_by_xpath('//span[@class="runtime"]'):
    rt.append(i.text)
for i in driver.find_elements_by_xpath('//span[@class="genre"]'):
    genre.append(i.text)
for i in driver.find_elements_by_xpath('//span[@class="ipl-rating-star__rating"]'):
    temp=i.text.replace('Rate','')
    ratings.append(temp)
ratings = list(filter(None, ratings))
count=0
for i in driver.find_elements_by_xpath('//p[@class="text-muted text-small"]'):
    count+=1
    if count%3==0:
        votes.append(i.text)
pd.DataFrame({'Name':data,'Year Span':year,'Runtime':rt,'Genre':genre,'Ratings':ratings,'Votes':votes})

,Name,Year Span,Runtime,Genre,Ratings,Votes
0,1. Game of Thrones,(2011–2019),57 min,"Action, Adventure, Drama",9.2,"Votes: 1,979,829"
1,2. Stranger Things,(2016– ),51 min,"Drama, Fantasy, Horror",8.7,"Votes: 985,545"
2,3. The Walking Dead,(2010–2022),44 min,"Drama, Horror, Thriller",8.2,"Votes: 943,650"
3,4. 13 Reasons Why,(2017–2020),60 min,"Drama, Mystery, Thriller",7.5,"Votes: 281,886"
4,5. The 100,(2014–2020),43 min,"Drama, Mystery, Sci-Fi",7.6,"Votes: 241,831"
...,...,...,...,...,...,...
95,96. Reign,(2013–2017),42 min,"Drama, Fantasy",7.4,"Votes: 48,516"
96,97. A Series of Unfortunate Events,(2017–2019),50 min,"Adventure, Comedy, Drama",7.8,"Votes: 59,152"
97,98. Criminal Minds,(2005–2020),42 min,"Crime, Drama, Mystery",8.1,"Votes: 188,696"
98,99. Scream: The TV Series,(2015–2019),45 min,"Comedy, Crime, Drama",7.1,"Votes: 39,989"
99,100. The Haunting of Hill House,(2018),572 min,"Drama, Horror, Mystery",8.6,"Votes: 226,171"

In [114]:
driver.close()